### ISSUE TITLE
typo in code?

### ISSUE THREAD

**Issue by stianfp** [ansibleplaybookbundle/awx-apb#4]
Should not {{ awx_secret_key }} be in ' or " in the file awx-apb/roles/provision-awx-apb/tasks/main.yml?

- name: Create AWX config map
  k8s_v1_config_map:
    name: awx-config
    namespace: '{{ namespace }}'
    data:
      secret_key: {{ awx_secret_key }}
      awx_settings: |
        import os
        import socket
        ADMINS = ()

**Comment by LorbusChris** [comment]
Please feel free to PR this :)
